In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('../adult_dataset.csv')

In [5]:
df

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [6]:
df.describe()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  str
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  str
 14  income          32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 3.7 MB

In [11]:
df_subset_1 = df[['workclass', 'education', 'capital.gain']]

In [12]:
df_subset_1

      workclass     education  capital.gain
0             ?       HS-grad             0
1       Private       HS-grad             0
2             ?  Some-college             0
3       Private       7th-8th             0
4       Private  Some-college             0
...         ...           ...           ...
32556   Private  Some-college             0
32557   Private    Assoc-acdm             0
32558   Private       HS-grad             0
32559   Private       HS-grad             0
32560   Private       HS-grad             0

[32561 rows x 3 columns]

In [14]:
df_subset_2 = df[['race', 'native.country']]

In [15]:
df_subset_2

        race native.country
0      White  United-States
1      White  United-States
2      Black  United-States
3      White  United-States
4      White  United-States
...      ...            ...
32556  White  United-States
32557  White  United-States
32558  White  United-States
32559  White  United-States
32560  White  United-States

[32561 rows x 2 columns]

In [16]:
merged_data = pd.concat([df_subset_1, df_subset_2], axis=1)

In [17]:
merged_data

      workclass     education  capital.gain   race native.country
0             ?       HS-grad             0  White  United-States
1       Private       HS-grad             0  White  United-States
2             ?  Some-college             0  Black  United-States
3       Private       7th-8th             0  White  United-States
4       Private  Some-college             0  White  United-States
...         ...           ...           ...    ...            ...
32556   Private  Some-college             0  White  United-States
32557   Private    Assoc-acdm             0  White  United-States
32558   Private       HS-grad             0  White  United-States
32559   Private       HS-grad             0  White  United-States
32560   Private       HS-grad             0  White  United-States

[32561 rows x 5 columns]

In [18]:
merged_data.sort_values(by=['capital.gain'], ascending=False)

              workclass     education  capital.gain   race native.country
1579       Self-emp-inc       HS-grad         99999  White              ?
1545            Private       Masters         99999  White  United-States
1546   Self-emp-not-inc     Bachelors         99999  White  United-States
1547            Private  Some-college         99999  Black  United-States
1548       Self-emp-inc       Masters         99999  White         Mexico
...                 ...           ...           ...    ...            ...
12              Private     Bachelors             0  White  United-States
13              Private       Masters             0  White  United-States
14                    ?     Doctorate             0  White  United-States
15              Private   Prof-school             0  White  United-States
32560           Private       HS-grad             0  White  United-States

[32561 rows x 5 columns]

In [19]:
merged_data.transpose()

,0,1,2,3,4,5,6,7,8,9,...,32551,32552,32553,32554,32555,32556,32557,32558,32559,32560
workclass,?,Private,?,Private,Private,Private,Private,State-gov,Federal-gov,Private,...,Self-emp-not-inc,Private,Private,Private,Private,Private,Private,Private,Private,Private
education,HS-grad,HS-grad,Some-college,7th-8th,Some-college,HS-grad,10th,Doctorate,HS-grad,Some-college,...,Some-college,10th,Assoc-voc,Masters,Masters,Some-college,Assoc-acdm,HS-grad,HS-grad,HS-grad
capital.gain,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
race,White,White,Black,White,White,White,White,White,White,White,...,White,Amer-Indian-Eskimo,White,Asian-Pac-Islander,White,White,White,White,White,White
native.country,United-States,United-States,United-States,United-States,United-States,United-States,United-States,United-States,United-States,?,...,United-States,United-States,United-States,Taiwan,United-States,United-States,United-States,United-States,United-States,United-States

In [20]:
merged_data.T

,0,1,2,3,4,5,6,7,8,9,...,32551,32552,32553,32554,32555,32556,32557,32558,32559,32560
workclass,?,Private,?,Private,Private,Private,Private,State-gov,Federal-gov,Private,...,Self-emp-not-inc,Private,Private,Private,Private,Private,Private,Private,Private,Private
education,HS-grad,HS-grad,Some-college,7th-8th,Some-college,HS-grad,10th,Doctorate,HS-grad,Some-college,...,Some-college,10th,Assoc-voc,Masters,Masters,Some-college,Assoc-acdm,HS-grad,HS-grad,HS-grad
capital.gain,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
race,White,White,Black,White,White,White,White,White,White,White,...,White,Amer-Indian-Eskimo,White,Asian-Pac-Islander,White,White,White,White,White,White
native.country,United-States,United-States,United-States,United-States,United-States,United-States,United-States,United-States,United-States,?,...,United-States,United-States,United-States,Taiwan,United-States,United-States,United-States,United-States,United-States,United-States

In [21]:
df

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [23]:
pd.melt(df, id_vars = ['education'], value_vars = ['capital.gain'])

          education      variable  value
0           HS-grad  capital.gain      0
1           HS-grad  capital.gain      0
2      Some-college  capital.gain      0
3           7th-8th  capital.gain      0
4      Some-college  capital.gain      0
...             ...           ...    ...
32556  Some-college  capital.gain      0
32557    Assoc-acdm  capital.gain      0
32558       HS-grad  capital.gain      0
32559       HS-grad  capital.gain      0
32560       HS-grad  capital.gain      0

[32561 rows x 3 columns]